### ISSUE TITLE
Track global phase

### ISSUE THREAD

**Issue by burgholzer** [cda-tum/zx#22]
Just a quick dump of a thought so that it does not get lost:

Right now in QCEC the best thing that can be shown by the ZX checker is equivalence up to global phase.
It might be surprising for some users, who would have expected their circuits to be truly equivalent, to receive the equivalent up to global phase result.
Would it be hard to also track the phase and correspondingly be able to give a precise answer?

**Comment by pehamTom** [comment]
Is now implemented.
