### ISSUE TITLE
Project doesn't install anything

### ISSUE THREAD

**Issue by yurivict** [cda-tum/zx#47]

**Comment by pehamTom** [comment]
Hi there, 

sorry there is not a lot to go on from the title of the issue alone. Can you provide a little bit more information?

Are you able to build the tests as described in the README? If you made a shallow clone you might need to run `git submodule update --init --recursive` from the project's root folder.

Building the project only builds a static library, no system-wide installs are made. The easiest way to use this library is if your project is also using CMake. See for example https://github.com/cda-tum/qfr where this library is included as a git submodule (in `extern/zx`) and included in `src/CMakeLists.txt`(https://github.com/cda-tum/qfr/blob/78a36084ff2ccce07f190b7395cdb8f44ed0de8c/src/CMakeLists.txt#L71).

**Comment by yurivict** [comment]
There is no ```install``` target because there are no ```install``` instructions in cmake scripts.
Projects are expected to install headers, libraries that they build, etc.

**Comment by yurivict** [comment]
If all projects would include their dependencies via git submodules compilation time would grow exponentially because every project would be compiled over and over again as part of various larger projects. This isn't sustainable. This is why every project should be able to install itself, should be built once and packaged, and used as dependency of other projects.

**Comment by burgholzer** [comment]
Thanks for the input. Providing the means to install the library is not planned for the near term future. That being said, we‘d happily accept a pull request that provides this feature though.

**Comment by yurivict** [comment]
Ok, I will wait for MQT projects to be able to install themselves before I create FreeBSD ports for them.
